HELP_FILES := \
	help/2-modifierrightoperand.md \
	help/absolutevalue_modulus.md \
	help/after_bind.md \
	help/assert_assertwithmessage.md \
	help/atop.md \
	help/before_bind.md \
	help/beginarray.md \
	help/beginblock.md \
	help/beginexpression.md \
	help/beginlist.md \
	help/catch.md \
	help/ceiling_maximum.md \
	help/cells.md \
	help/change.md \
	help/character.md \
	help/choose.md \
	help/classify_indexof.md \
	help/comment.md \
	help/conjugate_add.md \
	help/constant.md \
	help/currentfunction.md \
	help/currentmodifier.md \
	help/deduplicate_find.md \
	help/define.md \
	help/depth_match.md \
	help/depth.md \
	help/deshape_reshape.md \
	help/each.md \
	help/enclose_lessthan.md \
	help/endarray.md \
	help/endblock.md \
	help/endexpression.md \
	help/endlist.md \
	help/enlist_pair.md \
	help/exponential_power.md \
	help/export.md \
	help/firstcell_select.md \
	help/first_pick.md \
	help/floor_minimum.md \
	help/fold.md \
	help/gradedown_binsdown.md \
	help/gradeup_binsup.md \
	help/greaterthanorequalto.md \
	help/groupindices_group.md \
	help/header.md \
	help/identity_left.md \
	help/identity_right.md \
	help/indices_replicate.md \
	help/infinity.md \
	help/insert.md \
	help/join_jointo.md \
	help/leftargument.md \
	help/length_notequals.md \
	help/lessthanorequalto.md \
	help/markfirst_memberof.md \
	help/merge_greaterthan.md \
	help/minus.md \
	help/modifierleftoperand.md \
	help/namespacefield.md \
	help/negate_subtract.md \
	help/nextbody.md \
	help/nothing.md \
	help/not_span.md \
	help/nullcharacter.md \
	help/occurrencecount_progressiveindexof.md \
	help/over.md \
	help/pi.md \
	help/predicate.md \
	help/prefixes_take.md \
	help/range_windows.md \
	help/rank_equals.md \
	help/rank.md \
	help/README.md \
	help/reciprocal_divide.md \
	help/repeat.md \
	help/reverse_rotate.md \
	help/rightargument.md \
	help/scan.md \
	help/self_swap.md \
	help/separator.md \
	help/shape_notmatch.md \
	help/shiftafter.md \
	help/shiftbefore.md \
	help/sign_multiply.md \
	help/solo_couple.md \
	help/sortdown_or.md \
	help/sortup_and.md \
	help/squareroot_root.md \
	help/strand.md \
	help/string.md \
	help/suffixes_drop.md \
	help/system.md \
	help/table.md \
	help/transpose_reorderaxes.md \
	help/under.md \
	help/undo.md \
	help/valences.md
